apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: agones
  region: us-east-1
  version: "1.22"
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]
nodeGroups:
  - name: ng-system
    instanceType: m5.large
    desiredCapacity: 2
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::614954710407:policy/FleetIQpermissionsEC2
  - name: ng-agones
    instanceType: m5.xlarge
    desiredCapacity: 2
    labels:
      agones.dev/agones-system: "true"
    taints:
      agones.dev/agones-system: "true:NoExecute"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::614954710407:policy/FleetIQpermissionsEC2
