apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: minetest-autoscaler
spec:
  fleetName: minetest
  policy:
    type: Buffer
    buffer:
      bufferSize: 5
      minReplicas: 0
      maxReplicas: 20